// Mock data for the Blueprint Analysis Application

export const tenants = [
  {
    id: 'tenant-1',
    name: '大手建設株式会社',
    logo: '/logos/tenant1.png',
    settings: {
      notifications: {
        email: true,
        slack: false,
      },
      customFields: [],
    },
  },
  {
    id: 'tenant-2',
    name: '中堅建設工業',
    logo: '/logos/tenant2.png',
    settings: {
      notifications: {
        email: true,
        slack: true,
      },
      customFields: [],
    },
  },
];

export const users = [
  {
    id: 'user-1',
    tenantId: 'tenant-1',
    name: '山田太郎',
    email: 'yamada@example.com',
    role: 'general', // general, tenant_admin, system_admin
    avatar: '/avatars/user1.png',
  },
  {
    id: 'user-2',
    tenantId: 'tenant-1',
    name: '佐藤花子',
    email: 'sato@example.com',
    role: 'tenant_admin',
    avatar: '/avatars/user2.png',
  },
  {
    id: 'user-3',
    tenantId: 'tenant-2',
    name: '鈴木一郎',
    email: 'suzuki@example.com',
    role: 'general',
    avatar: '/avatars/user3.png',
  },
  {
    id: 'system-admin',
    tenantId: null,
    name: 'システム管理者',
    email: 'admin@datagrid.com',
    role: 'system_admin',
    avatar: '/avatars/admin.png',
  },
];

export const jobStatuses = {
  created: { label: '作成済み', color: 'gray' },
  file_uploading: { label: 'アップロード中', color: 'blue' },
  ready: { label: '準備完了', color: 'cyan' },
  processing: { label: '処理中', color: 'amber' },
  completed: { label: '完了', color: 'green' },
  failed: { label: '失敗', color: 'red' },
};

export const jobStatusOptions = Object.entries(jobStatuses).map(([value, meta]) => ({
  value,
  label: meta.label,
}));

export const taskTypes = {
  INSPECTION: {
    id: 'INSPECTION',
    name: 'BP Check',
    description: '構造図と施工図の整合性チェックを行います',
    icon: 'CircleCheckBig',
    color: 'green',
  },
  BOM: {
    id: 'BOM',
    name: 'BP Bom',
    description: '図面から部品表を自動抽出します',
    icon: 'FileText',
    color: 'blue',
  },
  SCAN: {
    id: 'SCAN',
    name: 'BP Scan',
    description: '図面のスキャンとタグ付けを行います',
    icon: 'ScanLine',
    color: 'purple',
  },
};

export const taskTypeOptions = Object.values(taskTypes).map((type) => ({
  value: type.id,
  label: type.name,
}));

export const mockJobs = [
  {
    id: 'job-001',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'INSPECTION',
    name: 'オフィスビル新築 - 基礎伏図検図',
    description: '基礎伏図の構造図と施工図の整合性確認（通り芯・柱・梁・配筋）',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-1', name: '基礎伏図_構造.pdf', size: 2048000, uploadedAt: '2025-11-20T10:00:00Z', preview: '/samples/blueprints/blueprint-05.jpg' },
      { id: 'file-2', name: '基礎伏図_施工.pdf', size: 3072000, uploadedAt: '2025-11-20T10:01:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
    ],
    createdAt: '2025-11-20T08:00:00Z',
    updatedAt: '2025-11-20T08:45:00Z',
    completedAt: '2025-11-20T08:45:00Z',
    results: {
      totalFindings: 12,
      okCount: 8,
      ngCount: 3,
      warningCount: 1,
      confirmedCount: 5,
      needsFixCount: 2,
    },
  },
  {
    id: 'job-002',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'BOM',
    name: 'マンション新築 - 配筋リスト生成',
    description: '配筋図から鉄筋リストを自動抽出',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-3', name: '配筋詳細図.pdf', size: 4096000, uploadedAt: '2025-11-20T09:30:00Z', preview: '/samples/blueprints/blueprint-11.jpg' },
    ],
    createdAt: '2025-11-20T09:00:00Z',
    updatedAt: '2025-11-20T09:35:00Z',
    completedAt: '2025-11-20T09:40:00Z',
    results: {
      totalParts: 45,
      extractedParts: 45,
      categories: ['主筋', 'あばら筋', 'スタラップ', 'フープ筋', '帯筋'],
    },
  },
  {
    id: 'job-003',
    tenantId: 'tenant-1',
    userId: 'user-2',
    taskType: 'INSPECTION',
    name: '商業施設増築 - 杭配置図検図',
    description: '杭伏図の構造図整合性確認',
    status: 'ready',
    progress: 0,
    files: [
      { id: 'file-4', name: '杭伏図_構造.pdf', size: 1024000, uploadedAt: '2025-11-20T07:00:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
    ],
    createdAt: '2025-11-20T07:00:00Z',
    updatedAt: '2025-11-20T07:05:00Z',
    completedAt: null,
    results: null,
  },
  {
    id: 'job-004',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'SCAN',
    name: '図面スキャン - 基礎配筋詳細',
    description: '基礎配筋図のスキャンとタグ付け',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-6', name: 'foundation_drawings_001.pdf', size: 5000000, uploadedAt: '2025-11-19T15:00:00Z', preview: '/samples/blueprints/blueprint-05.jpg' },
      { id: 'file-7', name: 'foundation_drawings_002.pdf', size: 4500000, uploadedAt: '2025-11-19T15:01:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
      { id: 'file-8', name: 'foundation_drawings_003.pdf', size: 4200000, uploadedAt: '2025-11-19T15:02:00Z', preview: '/samples/blueprints/blueprint-11.jpg' },
    ],
    createdAt: '2025-11-19T15:00:00Z',
    updatedAt: '2025-11-19T15:10:00Z',
    completedAt: '2025-11-19T15:10:00Z',
    results: {
      totalImages: 120,
      totalElements: 1523,
      scannedCount: 120,
      taggedCount: 98,
    },
  },
  {
    id: 'job-005',
    tenantId: 'tenant-2',
    userId: 'user-3',
    taskType: 'BOM',
    name: '工場新築 - 鉄骨部材リスト生成',
    description: '鉄骨詳細図から部材リストを自動抽出',
    status: 'failed',
    progress: 0,
    files: [
      { id: 'file-5', name: '鉄骨詳細図_破損.pdf', size: 512000, uploadedAt: '2025-11-19T14:00:00Z', preview: null },
    ],
    createdAt: '2025-11-19T14:00:00Z',
    updatedAt: '2025-11-19T14:02:00Z',
    completedAt: null,
    error: 'ファイル形式が不正です。PDFが破損している可能性があります。',
    results: null,
  },
];

// Mock BOM results data
export const mockBOMResults = [
  {
    id: 'bom-1',
    jobId: 'job-002',
    partNumber: 'D19-001',
    partName: 'D19 異形棒鋼（主筋）',
    specification: 'D19 SD345 L=6000',
    quantity: 48,
    unit: '本',
    category: '主筋',
    confidence: 0.95,
    extractedFrom: 'file-3',
    page: 1,
  },
  {
    id: 'bom-2',
    jobId: 'job-002',
    partNumber: 'D13-002',
    partName: 'D13 異形棒鋼（あばら筋）',
    specification: 'D13 SD295A @200',
    quantity: 120,
    unit: '本',
    category: 'あばら筋',
    confidence: 0.93,
    extractedFrom: 'file-3',
    page: 1,
  },
  {
    id: 'bom-3',
    jobId: 'job-002',
    partNumber: 'D10-003',
    partName: 'D10 異形棒鋼（スタラップ）',
    specification: 'D10 SD295A @150',
    quantity: 80,
    unit: '本',
    category: 'スタラップ',
    confidence: 0.91,
    extractedFrom: 'file-3',
    page: 1,
  },
  {
    id: 'bom-4',
    jobId: 'job-002',
    partNumber: 'P-A-001',
    partName: 'ベースプレート',
    specification: '200×200×10 SS400',
    quantity: 2,
    unit: '枚',
    category: '部品A',
    confidence: 0.89,
    extractedFrom: 'file-3',
    page: 2,
  },
  {
    id: 'bom-5',
    jobId: 'job-002',
    partNumber: 'P-B-001',
    partName: 'サポートブラケット',
    specification: '150×100×8 SS400',
    quantity: 4,
    unit: '個',
    category: '部品B',
    confidence: 0.87,
    extractedFrom: 'file-3',
    page: 2,
  },
];

// Mock scan results data (renamed from search)
export const mockScanResults = [
  {
    id: 'scan-1',
    jobId: 'job-004',
    fileId: 'file-6',
    fileName: 'foundation_drawings_001.pdf',
    page: 1,
    elementType: 'table',
    tagName: 'BOM',
    confidence: 0.92,
    aiComment: '部品表を検出しました。D19主筋配置の情報が含まれています。',
    boundingBox: { x: 100, y: 150, width: 350, height: 200 },
    polygon: [[100, 150], [450, 150], [450, 350], [100, 350]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-2',
    jobId: 'job-004',
    fileId: 'file-6',
    fileName: 'foundation_drawings_001.pdf',
    page: 1,
    elementType: 'text',
    tagName: 'title_block',
    confidence: 0.95,
    aiComment: '図面表題欄を検出しました。',
    boundingBox: { x: 500, y: 50, width: 300, height: 100 },
    polygon: [[500, 50], [800, 50], [800, 150], [500, 150]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'confirmed',
    userComment: '',
  },
  {
    id: 'scan-3',
    jobId: 'job-004',
    fileId: 'file-7',
    fileName: 'foundation_drawings_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: 'section_view',
    confidence: 0.88,
    aiComment: '断面図を検出しました。基礎梁の配筋詳細が含まれています。',
    boundingBox: { x: 150, y: 200, width: 400, height: 300 },
    polygon: [[150, 200], [550, 200], [550, 500], [150, 500]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-4',
    jobId: 'job-004',
    fileId: 'file-7',
    fileName: 'foundation_drawings_002.pdf',
    page: 2,
    elementType: 'text',
    tagName: 'dimension',
    confidence: 0.85,
    aiComment: '寸法注記を検出しました。4800mm間隔の表記があります。',
    boundingBox: { x: 200, y: 100, width: 250, height: 80 },
    polygon: [[200, 100], [450, 100], [450, 180], [200, 180]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-5',
    jobId: 'job-004',
    fileId: 'file-8',
    fileName: 'foundation_drawings_003.pdf',
    page: 1,
    elementType: 'table',
    tagName: 'BOM',
    confidence: 0.91,
    aiComment: '配筋リスト表を検出しました。',
    boundingBox: { x: 100, y: 400, width: 500, height: 150 },
    polygon: [[100, 400], [600, 400], [600, 550], [100, 550]],
    preview: '/samples/blueprints/blueprint-11.jpg',
    userAction: 'pending',
    userComment: '',
  },
];

export const mockInspectionResults = [
  {
    id: 'finding-1',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯整合性',
    findingType: '通り芯整合性',
    aiJudgment: 'OK',
    confidence: 0.95,
    aiComment: 'X1-Y1交点の通り芯位置が構造図と施工図で一致しています',
    aiInference: '実画像と図面の比較により、X1-Y1交点における通り芯の位置が正確に一致していることを確認しました。測定誤差は許容範囲内（±2mm）です。',
    userAction: 'confirmed',
    userComment: '確認済み',
    evidenceFile: 'file-1',
    evidencePage: 1,
    boundingBox: { x: 120, y: 150, width: 80, height: 60 },
    polygon: [[120, 150], [200, 150], [200, 210], [120, 210]],
  },
  {
    id: 'finding-2',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯整合性',
    findingType: '通り芯整合性',
    aiJudgment: 'NG',
    confidence: 0.88,
    aiComment: 'X3-Y2交点で通り芯の位置が5mm相違しています（構造: 3000, 施工: 2995）',
    aiInference: '施工図と構造図を比較した結果、X3-Y2交点において5mmの位置ズレを検出しました。この誤差は許容範囲を超えており、是正が必要です。',
    userAction: 'needs_fix',
    userComment: '要修正。構造図の通り芯X3を確認',
    evidenceFile: 'file-1',
    evidencePage: 2,
    boundingBox: { x: 280, y: 220, width: 70, height: 55 },
    polygon: [[280, 220], [350, 220], [350, 275], [280, 275]],
  },
  {
    id: 'finding-3',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '配筋整合性',
    findingType: '配筋整合性',
    aiJudgment: 'WARNING',
    confidence: 0.72,
    aiComment: 'C1柱（X2-Y3交点）の主筋本数が異なる可能性があります（構造: 12-D25, 施工: 不明瞭）',
    aiInference: '画像解析により配筋パターンを検出しましたが、施工図の表記が不明瞭なため確定判定ができません。現場確認を推奨します。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 1,
    boundingBox: { x: 180, y: 280, width: 90, height: 70 },
    polygon: [[180, 280], [270, 280], [270, 350], [180, 350]],
  },
  {
    id: 'finding-4',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '柱寸法整合性',
    findingType: '柱寸法整合性',
    aiJudgment: 'OK',
    confidence: 0.92,
    aiComment: 'C2柱（X4-Y1交点）の断面寸法が一致しています（600×600）',
    aiInference: 'C2柱の断面寸法600×600mmが構造図と施工図で正確に一致していることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 3,
    boundingBox: { x: 350, y: 120, width: 65, height: 50 },
    polygon: [[350, 120], [415, 120], [415, 170], [350, 170]],
  },
  {
    id: 'finding-5',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯間隔',
    findingType: '通り芯間隔',
    aiJudgment: 'OK',
    confidence: 0.96,
    aiComment: 'X1-X2間の通り芯間隔が正確です（4800mm）',
    aiInference: 'X1-X2間の通り芯間隔4800mmが設計図通りであることを確認しました。測定精度は高い信頼度です。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 1,
    boundingBox: { x: 420, y: 180, width: 75, height: 60 },
    polygon: [[420, 180], [495, 180], [495, 240], [420, 240]],
  },
  {
    id: 'finding-6',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '基礎梁配筋',
    findingType: '基礎梁配筋',
    aiJudgment: 'NG',
    confidence: 0.71,
    aiComment: 'F1基礎梁（X2-Y1からX3-Y1）の主筋配置が不明確です。要確認',
    aiInference: '基礎梁F1の主筋配置について、施工図と構造図の間に不整合が検出されました。詳細確認が必要です。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 2,
    boundingBox: { x: 150, y: 320, width: 85, height: 55 },
    polygon: [[150, 320], [235, 320], [235, 375], [150, 375]],
  },
  {
    id: 'finding-7',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '梁断面整合性',
    findingType: '梁断面整合性',
    aiJudgment: 'OK',
    confidence: 0.94,
    aiComment: 'G1梁（X1-Y2からX3-Y2スパン）の断面寸法が一致しています（400×800）',
    aiInference: 'G1梁の断面400×800mmが設計通りであることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 4,
    boundingBox: { x: 250, y: 100, width: 70, height: 45 },
    polygon: [[250, 100], [320, 100], [320, 145], [250, 145]],
  },
  {
    id: 'finding-8',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '柱配筋整合性',
    findingType: '柱配筋整合性',
    aiJudgment: 'OK',
    confidence: 0.89,
    aiComment: 'C1柱（X1-Y1交点）の配筋パターンが一致しています（16-D25 + D10@100）',
    aiInference: 'C1柱の配筋パターン（主筋16-D25、帯筋D10@100）が設計図と一致していることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 3,
    boundingBox: { x: 320, y: 250, width: 80, height: 65 },
    polygon: [[320, 250], [400, 250], [400, 315], [320, 315]],
  },
  {
    id: 'finding-9',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯間隔',
    findingType: '通り芯間隔',
    aiJudgment: 'OK',
    confidence: 0.97,
    aiComment: 'Y軸方向の通り芯間隔が正確です（Y1-Y2: 6000mm, Y2-Y3: 6000mm）',
    aiInference: 'Y軸方向の通り芯間隔が設計通り6000mmであることを高精度で確認しました。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 2,
    boundingBox: { x: 180, y: 380, width: 75, height: 50 },
    polygon: [[180, 380], [255, 380], [255, 430], [180, 430]],
  },
  {
    id: 'finding-10',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '基礎レベル整合性',
    findingType: '基礎レベル整合性',
    aiJudgment: 'NG',
    confidence: 0.81,
    aiComment: 'F1基礎（X2-Y2交点）の天端レベル表記が10mm異なります（構造: FL-500, 施工: FL-490）',
    aiInference: '基礎天端レベルに10mmの差異を検出しました。この誤差は施工精度に影響する可能性があります。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 1,
    boundingBox: { x: 450, y: 300, width: 70, height: 55 },
    polygon: [[450, 300], [520, 300], [520, 355], [450, 355]],
  },
  {
    id: 'finding-11',
    jobId: 'job-001',
    fileId: 'file-2',
    type: 'スラブ厚整合性',
    findingType: 'スラブ厚整合性',
    aiJudgment: 'OK',
    confidence: 0.93,
    aiComment: '基礎スラブ厚が一致しています（150mm）',
    aiInference: '基礎スラブ厚150mmが構造図と施工図で一致していることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 4,
    boundingBox: { x: 100, y: 420, width: 85, height: 50 },
    polygon: [[100, 420], [185, 420], [185, 470], [100, 470]],
  },
  {
    id: 'finding-12',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '梁主筋配筋',
    findingType: '梁主筋配筋',
    aiJudgment: 'OK',
    confidence: 0.91,
    aiComment: 'G2梁（X4-Y3からX5-Y3）の主筋配置が正確です（上筋: 4-D22, 下筋: 3-D22）',
    aiInference: 'G2梁の主筋配置（上筋4-D22、下筋3-D22）が設計図通りであることを確認しました。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 5,
    boundingBox: { x: 380, y: 380, width: 80, height: 55 },
    polygon: [[380, 380], [460, 380], [460, 435], [380, 435]],
  },
];

// Simulated async processing
export const simulateJobProcessing = (jobId, onProgress) => {
  return new Promise((resolve) => {
    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.random() * 15;
      if (progress >= 100) {
        progress = 100;
        clearInterval(interval);
        onProgress(100);
        resolve();
      } else {
        onProgress(Math.floor(progress));
      }
    }, 1000);
  });
};

// Helper functions
export const getUserById = (userId) => users.find(u => u.id === userId);
export const getTenantById = (tenantId) => tenants.find(t => t.id === tenantId);
export const getJobById = (jobId) => mockJobs.find(j => j.id === jobId);
export const getJobsByTenant = (tenantId) => mockJobs.filter(j => j.tenantId === tenantId);
export const getJobsByUser = (userId) => mockJobs.filter(j => j.userId === userId);
export const getInspectionResults = (jobId) => mockInspectionResults.filter(r => r.jobId === jobId);
export const getBOMResults = (jobId) => mockBOMResults.filter(r => r.jobId === jobId);
export const getScanResults = (jobId) => mockScanResults.filter(r => r.jobId === jobId);

// Backwards compatibility alias
export const getSearchResults = getScanResults;
