// Mock data for the Blueprint Analysis Application

export const tenants = [
  {
    id: 'tenant-1',
    name: '大手建設株式会社',
    logo: '/logos/tenant1.png',
    settings: {
      notifications: {
        email: true,
        slack: false,
      },
      customFields: [],
    },
  },
  {
    id: 'tenant-2',
    name: '中堅建設工業',
    logo: '/logos/tenant2.png',
    settings: {
      notifications: {
        email: true,
        slack: true,
      },
      customFields: [],
    },
  },
];

export const users = [
  {
    id: 'user-1',
    tenantId: 'tenant-1',
    name: '山田太郎',
    email: 'yamada@example.com',
    role: 'general', // general, tenant_admin, system_admin
    avatar: '/avatars/user1.png',
  },
  {
    id: 'user-2',
    tenantId: 'tenant-1',
    name: '佐藤花子',
    email: 'sato@example.com',
    role: 'tenant_admin',
    avatar: '/avatars/user2.png',
  },
  {
    id: 'user-3',
    tenantId: 'tenant-2',
    name: '鈴木一郎',
    email: 'suzuki@example.com',
    role: 'general',
    avatar: '/avatars/user3.png',
  },
  {
    id: 'system-admin',
    tenantId: null,
    name: 'システム管理者',
    email: 'admin@datagrid.com',
    role: 'system_admin',
    avatar: '/avatars/admin.png',
  },
];

export const jobStatuses = {
  created: { label: '作成済み', color: 'gray' },
  file_uploading: { label: 'アップロード中', color: 'blue' },
  ready: { label: '準備完了', color: 'cyan' },
  processing: { label: '処理中', color: 'amber' },
  completed: { label: '完了', color: 'green' },
  failed: { label: '失敗', color: 'red' },
};

export const jobStatusOptions = Object.entries(jobStatuses).map(([value, meta]) => ({
  value,
  label: meta.label,
}));

export const taskTypes = {
  INSPECTION: {
    id: 'INSPECTION',
    name: 'BP Check',
    description: '構造図と施工図の整合性チェックを行います',
    icon: 'CircleCheckBig',
    color: 'green',
  },
  BOM: {
    id: 'BOM',
    name: 'BP Bom',
    description: '図面から部品表を自動抽出します',
    icon: 'FileText',
    color: 'blue',
  },
  SCAN: {
    id: 'SCAN',
    name: 'BP Scan',
    description: '図面のスキャンとタグ付けを行います',
    icon: 'ScanLine',
    color: 'purple',
  },
};

export const taskTypeOptions = Object.values(taskTypes).map((type) => ({
  value: type.id,
  label: type.name,
}));

export const mockJobs = [
  {
    id: 'job-001',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'INSPECTION',
    name: 'オフィスビル新築 - 基礎伏図検図',
    description: '基礎伏図の構造図と施工図の整合性確認（通り芯・柱・梁・配筋）',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-1', name: '基礎伏図_構造.pdf', size: 2048000, uploadedAt: '2025-11-20T10:00:00Z', preview: '/samples/blueprints/blueprint-05.jpg' },
      { id: 'file-2', name: '基礎伏図_施工.pdf', size: 3072000, uploadedAt: '2025-11-20T10:01:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
    ],
    createdAt: '2025-11-20T08:00:00Z',
    updatedAt: '2025-11-20T08:45:00Z',
    completedAt: '2025-11-20T08:45:00Z',
    results: {
      totalFindings: 12,
      okCount: 8,
      ngCount: 3,
      warningCount: 1,
      confirmedCount: 5,
      needsFixCount: 2,
    },
  },
  {
    id: 'job-006',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'SCAN',
    name: '図面スキャン - 鉄骨詳細図',
    description: '鉄骨詳細図のスキャンとタグ付け',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-9', name: 'steel_detail_001.pdf', size: 3500000, uploadedAt: '2025-11-22T09:00:00Z', preview: '/samples/blueprints/blueprint-05.jpg' },
      { id: 'file-10', name: 'steel_detail_002.pdf', size: 3200000, uploadedAt: '2025-11-22T09:01:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
    ],
    createdAt: '2025-11-22T08:30:00Z',
    updatedAt: '2025-11-22T09:20:00Z',
    completedAt: '2025-11-22T09:20:00Z',
    results: {
      totalImages: 85,
      totalElements: 956,
      scannedCount: 85,
      taggedCount: 78,
    },
  },
  {
    id: 'job-007',
    tenantId: 'tenant-1',
    userId: 'user-2',
    taskType: 'SCAN',
    name: '図面スキャン - 設備配管図',
    description: '設備配管図のスキャンとタグ付け処理中',
    status: 'processing',
    progress: 65,
    files: [
      { id: 'file-11', name: 'plumbing_001.pdf', size: 4100000, uploadedAt: '2025-11-25T10:00:00Z', preview: '/samples/blueprints/blueprint-11.jpg' },
    ],
    createdAt: '2025-11-25T09:45:00Z',
    updatedAt: '2025-11-25T10:15:00Z',
    completedAt: null,
    results: null,
  },
  {
    id: 'job-008',
    tenantId: 'tenant-2',
    userId: 'user-3',
    taskType: 'SCAN',
    name: '図面スキャン - 電気設備図',
    description: '電気設備図面のスキャンとタグ付け',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-12', name: 'electrical_001.pdf', size: 2800000, uploadedAt: '2025-11-21T14:00:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
      { id: 'file-13', name: 'electrical_002.pdf', size: 2500000, uploadedAt: '2025-11-21T14:01:00Z', preview: '/samples/blueprints/blueprint-05.jpg' },
    ],
    createdAt: '2025-11-21T13:30:00Z',
    updatedAt: '2025-11-21T14:30:00Z',
    completedAt: '2025-11-21T14:30:00Z',
    results: {
      totalImages: 64,
      totalElements: 845,
      scannedCount: 64,
      taggedCount: 61,
    },
  },
  {
    id: 'job-002',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'BOM',
    name: 'マンション新築 - 配筋リスト生成',
    description: '配筋図から鉄筋リストを自動抽出',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-3', name: '配筋詳細図.pdf', size: 4096000, uploadedAt: '2025-11-20T09:30:00Z', preview: '/samples/blueprints/blueprint-11.jpg' },
    ],
    createdAt: '2025-11-20T09:00:00Z',
    updatedAt: '2025-11-20T09:35:00Z',
    completedAt: '2025-11-20T09:40:00Z',
    results: {
      totalParts: 45,
      extractedParts: 45,
      categories: ['主筋', 'あばら筋', 'スタラップ', 'フープ筋', '帯筋'],
    },
  },
  {
    id: 'job-003',
    tenantId: 'tenant-1',
    userId: 'user-2',
    taskType: 'INSPECTION',
    name: '商業施設増築 - 杭配置図検図',
    description: '杭伏図の構造図整合性確認',
    status: 'ready',
    progress: 0,
    files: [
      { id: 'file-4', name: '杭伏図_構造.pdf', size: 1024000, uploadedAt: '2025-11-20T07:00:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
    ],
    createdAt: '2025-11-20T07:00:00Z',
    updatedAt: '2025-11-20T07:05:00Z',
    completedAt: null,
    results: null,
  },
  {
    id: 'job-004',
    tenantId: 'tenant-1',
    userId: 'user-1',
    taskType: 'SCAN',
    name: '図面スキャン - 基礎配筋詳細',
    description: '基礎配筋図のスキャンとタグ付け',
    status: 'completed',
    progress: 100,
    files: [
      { id: 'file-6', name: 'foundation_drawings_001.pdf', size: 5000000, uploadedAt: '2025-11-19T15:00:00Z', preview: '/samples/blueprints/blueprint-05.jpg' },
      { id: 'file-7', name: 'foundation_drawings_002.pdf', size: 4500000, uploadedAt: '2025-11-19T15:01:00Z', preview: '/samples/blueprints/blueprint-09.jpg' },
      { id: 'file-8', name: 'foundation_drawings_003.pdf', size: 4200000, uploadedAt: '2025-11-19T15:02:00Z', preview: '/samples/blueprints/blueprint-11.jpg' },
    ],
    createdAt: '2025-11-19T15:00:00Z',
    updatedAt: '2025-11-19T15:10:00Z',
    completedAt: '2025-11-19T15:10:00Z',
    results: {
      totalImages: 120,
      totalElements: 1523,
      scannedCount: 120,
      taggedCount: 98,
    },
  },
  {
    id: 'job-005',
    tenantId: 'tenant-2',
    userId: 'user-3',
    taskType: 'BOM',
    name: '工場新築 - 鉄骨部材リスト生成',
    description: '鉄骨詳細図から部材リストを自動抽出',
    status: 'failed',
    progress: 0,
    files: [
      { id: 'file-5', name: '鉄骨詳細図_破損.pdf', size: 512000, uploadedAt: '2025-11-19T14:00:00Z', preview: null },
    ],
    createdAt: '2025-11-19T14:00:00Z',
    updatedAt: '2025-11-19T14:02:00Z',
    completedAt: null,
    error: 'ファイル形式が不正です。PDFが破損している可能性があります。',
    results: null,
  },
];

// Mock BOM results data
export const mockBOMResults = [
  {
    id: 'bom-1',
    jobId: 'job-002',
    partNumber: 'D19-001',
    partName: 'D19 異形棒鋼（主筋）',
    specification: 'D19 SD345 L=6000',
    quantity: 48,
    unit: '本',
    category: '主筋',
    confidence: 0.95,
    extractedFrom: 'file-3',
    page: 1,
  },
  {
    id: 'bom-2',
    jobId: 'job-002',
    partNumber: 'D13-002',
    partName: 'D13 異形棒鋼（あばら筋）',
    specification: 'D13 SD295A @200',
    quantity: 120,
    unit: '本',
    category: 'あばら筋',
    confidence: 0.93,
    extractedFrom: 'file-3',
    page: 1,
  },
  {
    id: 'bom-3',
    jobId: 'job-002',
    partNumber: 'D10-003',
    partName: 'D10 異形棒鋼（スタラップ）',
    specification: 'D10 SD295A @150',
    quantity: 80,
    unit: '本',
    category: 'スタラップ',
    confidence: 0.91,
    extractedFrom: 'file-3',
    page: 1,
  },
  {
    id: 'bom-4',
    jobId: 'job-002',
    partNumber: 'P-A-001',
    partName: 'ベースプレート',
    specification: '200×200×10 SS400',
    quantity: 2,
    unit: '枚',
    category: '部品A',
    confidence: 0.89,
    extractedFrom: 'file-3',
    page: 2,
  },
  {
    id: 'bom-5',
    jobId: 'job-002',
    partNumber: 'P-B-001',
    partName: 'サポートブラケット',
    specification: '150×100×8 SS400',
    quantity: 4,
    unit: '個',
    category: '部品B',
    confidence: 0.87,
    extractedFrom: 'file-3',
    page: 2,
  },
];

// Mock scan results data (renamed from search)
export const mockScanResults = [
  // Scan results for job-004 (基礎配筋詳細)
  {
    id: 'scan-1',
    jobId: 'job-004',
    fileId: 'file-6',
    fileName: 'foundation_drawings_001.pdf',
    page: 1,
    elementType: 'table',
    tagName: '配筋表',
    tagCategory: 'BOM',
    confidence: 0.92,
    aiComment: '部品表を検出しました。D19主筋配置の情報が含まれています。',
    detailedInfo: {
      rowCount: 12,
      colCount: 5,
      headerRow: ['部材', '径', '本数', '長さ', '備考'],
    },
    boundingBox: { x: 100, y: 150, width: 350, height: 200 },
    polygon: [[100, 150], [450, 150], [450, 350], [100, 350]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-2',
    jobId: 'job-004',
    fileId: 'file-6',
    fileName: 'foundation_drawings_001.pdf',
    page: 1,
    elementType: 'text',
    tagName: '図面表題欄',
    tagCategory: 'title_block',
    confidence: 0.95,
    aiComment: '図面表題欄を検出しました。図面番号: S-101、図面名: 基礎伏図',
    detailedInfo: {
      drawingNumber: 'S-101',
      drawingName: '基礎伏図',
      scale: '1/50',
      date: '2025-11-01',
    },
    boundingBox: { x: 500, y: 50, width: 300, height: 100 },
    polygon: [[500, 50], [800, 50], [800, 150], [500, 150]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'confirmed',
    userComment: '確認済み',
  },
  {
    id: 'scan-3',
    jobId: 'job-004',
    fileId: 'file-6',
    fileName: 'foundation_drawings_001.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '平面図',
    tagCategory: 'plan_view',
    confidence: 0.94,
    aiComment: '基礎伏図（平面図）を検出しました。通り芯X1〜X5、Y1〜Y4を含みます。',
    detailedInfo: {
      gridLines: ['X1', 'X2', 'X3', 'X4', 'X5', 'Y1', 'Y2', 'Y3', 'Y4'],
      foundationType: '独立基礎',
    },
    boundingBox: { x: 50, y: 200, width: 400, height: 300 },
    polygon: [[50, 200], [450, 200], [450, 500], [50, 500]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-4',
    jobId: 'job-004',
    fileId: 'file-6',
    fileName: 'foundation_drawings_001.pdf',
    page: 1,
    elementType: 'text',
    tagName: '寸法注記',
    tagCategory: 'dimension',
    confidence: 0.89,
    aiComment: '寸法注記を検出しました。通り芯間隔4800mmの表記があります。',
    detailedInfo: {
      dimensions: ['4800', '6000', '4800', '6000'],
      unit: 'mm',
    },
    boundingBox: { x: 60, y: 180, width: 380, height: 40 },
    polygon: [[60, 180], [440, 180], [440, 220], [60, 220]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-5',
    jobId: 'job-004',
    fileId: 'file-7',
    fileName: 'foundation_drawings_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '断面図',
    tagCategory: 'section_view',
    confidence: 0.88,
    aiComment: '断面図を検出しました。基礎梁の配筋詳細が含まれています。',
    detailedInfo: {
      sectionName: 'A-A断面',
      beamSize: '400×800',
      reinforcement: '上筋4-D22、下筋3-D22',
    },
    boundingBox: { x: 150, y: 200, width: 400, height: 300 },
    polygon: [[150, 200], [550, 200], [550, 500], [150, 500]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-6',
    jobId: 'job-004',
    fileId: 'file-7',
    fileName: 'foundation_drawings_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '配筋詳細図',
    tagCategory: 'rebar_detail',
    confidence: 0.91,
    aiComment: '配筋詳細図を検出しました。柱・梁接合部の配筋が含まれています。',
    detailedInfo: {
      mainBars: '16-D25',
      stirrups: 'D10@100',
      hoops: 'D10@150',
    },
    boundingBox: { x: 580, y: 200, width: 250, height: 200 },
    polygon: [[580, 200], [830, 200], [830, 400], [580, 400]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'confirmed',
    userComment: '',
  },
  {
    id: 'scan-7',
    jobId: 'job-004',
    fileId: 'file-7',
    fileName: 'foundation_drawings_002.pdf',
    page: 2,
    elementType: 'text',
    tagName: '凡例',
    tagCategory: 'legend',
    confidence: 0.85,
    aiComment: '凡例を検出しました。配筋記号の説明が含まれています。',
    detailedInfo: {
      symbols: ['D19: 異形棒鋼φ19', 'D22: 異形棒鋼φ22', 'D25: 異形棒鋼φ25'],
    },
    boundingBox: { x: 600, y: 450, width: 200, height: 100 },
    polygon: [[600, 450], [800, 450], [800, 550], [600, 550]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-8',
    jobId: 'job-004',
    fileId: 'file-8',
    fileName: 'foundation_drawings_003.pdf',
    page: 1,
    elementType: 'table',
    tagName: '配筋リスト',
    tagCategory: 'BOM',
    confidence: 0.91,
    aiComment: '配筋リスト表を検出しました。全45種類の配筋情報が含まれています。',
    detailedInfo: {
      totalItems: 45,
      categories: ['主筋', 'あばら筋', 'スタラップ', 'フープ筋'],
    },
    boundingBox: { x: 100, y: 400, width: 500, height: 150 },
    polygon: [[100, 400], [600, 400], [600, 550], [100, 550]],
    preview: '/samples/blueprints/blueprint-11.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-9',
    jobId: 'job-004',
    fileId: 'file-8',
    fileName: 'foundation_drawings_003.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '基礎断面詳細',
    tagCategory: 'detail_view',
    confidence: 0.87,
    aiComment: '基礎断面詳細図を検出しました。杭頭接合部の詳細です。',
    detailedInfo: {
      pileType: 'PHC杭φ400',
      embedmentDepth: '100mm',
    },
    boundingBox: { x: 100, y: 100, width: 350, height: 250 },
    polygon: [[100, 100], [450, 100], [450, 350], [100, 350]],
    preview: '/samples/blueprints/blueprint-11.jpg',
    userAction: 'pending',
    userComment: '',
  },
  // Scan results for job-006 (鉄骨詳細図)
  {
    id: 'scan-10',
    jobId: 'job-006',
    fileId: 'file-9',
    fileName: 'steel_detail_001.pdf',
    page: 1,
    elementType: 'table',
    tagName: '鉄骨部材表',
    tagCategory: 'BOM',
    confidence: 0.94,
    aiComment: '鉄骨部材リストを検出しました。H形鋼の仕様情報が含まれています。',
    detailedInfo: {
      totalParts: 28,
      categories: ['柱', '大梁', '小梁', 'ブレース'],
      mainMaterial: 'SS400',
    },
    boundingBox: { x: 80, y: 120, width: 400, height: 180 },
    polygon: [[80, 120], [480, 120], [480, 300], [80, 300]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-11',
    jobId: 'job-006',
    fileId: 'file-9',
    fileName: 'steel_detail_001.pdf',
    page: 1,
    elementType: 'text',
    tagName: '図面表題欄',
    tagCategory: 'title_block',
    confidence: 0.97,
    aiComment: '図面表題欄を検出しました。鉄骨詳細図-A棟、図番S-201',
    detailedInfo: {
      drawingNumber: 'S-201',
      drawingName: '鉄骨詳細図-A棟',
      scale: '1/30',
    },
    boundingBox: { x: 550, y: 30, width: 280, height: 90 },
    polygon: [[550, 30], [830, 30], [830, 120], [550, 120]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'confirmed',
    userComment: '',
  },
  {
    id: 'scan-12',
    jobId: 'job-006',
    fileId: 'file-9',
    fileName: 'steel_detail_001.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '柱脚詳細',
    tagCategory: 'connection_detail',
    confidence: 0.89,
    aiComment: '柱脚詳細図を検出しました。露出柱脚の詳細が含まれています。',
    detailedInfo: {
      baseType: '露出柱脚',
      anchorBolts: 'M24×6本',
      basePlate: 'PL-22×400×400',
    },
    boundingBox: { x: 120, y: 320, width: 350, height: 200 },
    polygon: [[120, 320], [470, 320], [470, 520], [120, 520]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-13',
    jobId: 'job-006',
    fileId: 'file-9',
    fileName: 'steel_detail_001.pdf',
    page: 2,
    elementType: 'figure',
    tagName: '柱梁接合部',
    tagCategory: 'connection_detail',
    confidence: 0.92,
    aiComment: '柱梁接合部詳細図を検出しました。通しダイアフラム形式です。',
    detailedInfo: {
      connectionType: '通しダイアフラム',
      weldType: '完全溶込み溶接',
    },
    boundingBox: { x: 200, y: 150, width: 400, height: 300 },
    polygon: [[200, 150], [600, 150], [600, 450], [200, 450]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-14',
    jobId: 'job-006',
    fileId: 'file-10',
    fileName: 'steel_detail_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '鉄骨伏図',
    tagCategory: 'plan_view',
    confidence: 0.91,
    aiComment: '鉄骨伏図を検出しました。2階床レベルの鉄骨配置です。',
    detailedInfo: {
      floorLevel: '2FL',
      gridLines: ['X1〜X5', 'Y1〜Y4'],
    },
    boundingBox: { x: 50, y: 80, width: 500, height: 350 },
    polygon: [[50, 80], [550, 80], [550, 430], [50, 430]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-15',
    jobId: 'job-006',
    fileId: 'file-10',
    fileName: 'steel_detail_002.pdf',
    page: 1,
    elementType: 'text',
    tagName: '部材記号',
    tagCategory: 'dimension',
    confidence: 0.86,
    aiComment: '部材記号を検出しました。H-400×200×8×13の表記があります。',
    detailedInfo: {
      memberType: '大梁',
      section: 'H-400×200×8×13',
      material: 'SS400',
    },
    boundingBox: { x: 350, y: 280, width: 150, height: 50 },
    polygon: [[350, 280], [500, 280], [500, 330], [350, 330]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-16',
    jobId: 'job-006',
    fileId: 'file-10',
    fileName: 'steel_detail_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: 'ブレース詳細',
    tagCategory: 'brace_detail',
    confidence: 0.88,
    aiComment: 'ブレース詳細図を検出しました。ターンバックル式ブレースです。',
    detailedInfo: {
      braceType: 'ターンバックル',
      rodDiameter: 'M20',
    },
    boundingBox: { x: 600, y: 300, width: 200, height: 180 },
    polygon: [[600, 300], [800, 300], [800, 480], [600, 480]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  // Scan results for job-008 (電気設備図)
  {
    id: 'scan-17',
    jobId: 'job-008',
    fileId: 'file-12',
    fileName: 'electrical_001.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '単線結線図',
    tagCategory: 'wiring_diagram',
    confidence: 0.93,
    aiComment: '単線結線図を検出しました。主幹ブレーカーからの分岐回路が含まれています。',
    detailedInfo: {
      mainBreaker: '400A',
      branchCircuits: 12,
      voltage: '三相200V',
    },
    boundingBox: { x: 100, y: 100, width: 450, height: 350 },
    polygon: [[100, 100], [550, 100], [550, 450], [100, 450]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-18',
    jobId: 'job-008',
    fileId: 'file-12',
    fileName: 'electrical_001.pdf',
    page: 1,
    elementType: 'table',
    tagName: '負荷設備表',
    tagCategory: 'circuit_schedule',
    confidence: 0.95,
    aiComment: '負荷設備表を検出しました。各回路の容量が記載されています。',
    detailedInfo: {
      totalLoad: '120kVA',
      circuits: [
        { name: '照明回路', capacity: '30A' },
        { name: 'コンセント回路', capacity: '20A' },
        { name: '動力回路', capacity: '50A' },
      ],
    },
    boundingBox: { x: 580, y: 150, width: 250, height: 300 },
    polygon: [[580, 150], [830, 150], [830, 450], [580, 450]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'confirmed',
    userComment: '回路容量確認済み',
  },
  {
    id: 'scan-19',
    jobId: 'job-008',
    fileId: 'file-12',
    fileName: 'electrical_001.pdf',
    page: 1,
    elementType: 'text',
    tagName: '図面表題欄',
    tagCategory: 'title_block',
    confidence: 0.96,
    aiComment: '図面表題欄を検出しました。電気設備単線図、図番E-101',
    detailedInfo: {
      drawingNumber: 'E-101',
      drawingName: '電気設備単線図',
      scale: 'N.S.',
    },
    boundingBox: { x: 650, y: 480, width: 180, height: 70 },
    polygon: [[650, 480], [830, 480], [830, 550], [650, 550]],
    preview: '/samples/blueprints/blueprint-09.jpg',
    userAction: 'confirmed',
    userComment: '',
  },
  {
    id: 'scan-20',
    jobId: 'job-008',
    fileId: 'file-13',
    fileName: 'electrical_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '電気設備平面図',
    tagCategory: 'floor_plan',
    confidence: 0.90,
    aiComment: '電気設備平面図を検出しました。照明器具とコンセントの配置が含まれています。',
    detailedInfo: {
      floor: '1F',
      lightingCount: 45,
      outletCount: 32,
    },
    boundingBox: { x: 80, y: 80, width: 550, height: 400 },
    polygon: [[80, 80], [630, 80], [630, 480], [80, 480]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-21',
    jobId: 'job-008',
    fileId: 'file-13',
    fileName: 'electrical_002.pdf',
    page: 1,
    elementType: 'text',
    tagName: '凡例',
    tagCategory: 'legend',
    confidence: 0.88,
    aiComment: '凡例を検出しました。電気記号の説明が含まれています。',
    detailedInfo: {
      symbols: ['○: ダウンライト', '□: シーリングライト', '△: 非常照明', '◎: コンセント'],
    },
    boundingBox: { x: 650, y: 400, width: 180, height: 120 },
    polygon: [[650, 400], [830, 400], [830, 520], [650, 520]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
  {
    id: 'scan-22',
    jobId: 'job-008',
    fileId: 'file-13',
    fileName: 'electrical_002.pdf',
    page: 1,
    elementType: 'figure',
    tagName: '分電盤詳細',
    tagCategory: 'panel_detail',
    confidence: 0.85,
    aiComment: '分電盤詳細図を検出しました。P-1分電盤の内部配置です。',
    detailedInfo: {
      panelName: 'P-1',
      capacity: '100A',
      circuits: 24,
    },
    boundingBox: { x: 650, y: 100, width: 180, height: 280 },
    polygon: [[650, 100], [830, 100], [830, 380], [650, 380]],
    preview: '/samples/blueprints/blueprint-05.jpg',
    userAction: 'pending',
    userComment: '',
  },
];

export const mockInspectionResults = [
  {
    id: 'finding-1',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯整合性',
    findingType: '通り芯整合性',
    aiJudgment: 'OK',
    confidence: 0.95,
    aiComment: 'X1-Y1交点の通り芯位置が構造図と施工図で一致しています',
    aiInference: '実画像と図面の比較により、X1-Y1交点における通り芯の位置が正確に一致していることを確認しました。測定誤差は許容範囲内（±2mm）です。',
    userAction: 'confirmed',
    userComment: '確認済み',
    evidenceFile: 'file-1',
    evidencePage: 1,
    boundingBox: { x: 120, y: 150, width: 80, height: 60 },
    polygon: [[120, 150], [200, 150], [200, 210], [120, 210]],
  },
  {
    id: 'finding-2',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯整合性',
    findingType: '通り芯整合性',
    aiJudgment: 'NG',
    confidence: 0.88,
    aiComment: 'X3-Y2交点で通り芯の位置が5mm相違しています（構造: 3000, 施工: 2995）',
    aiInference: '施工図と構造図を比較した結果、X3-Y2交点において5mmの位置ズレを検出しました。この誤差は許容範囲を超えており、是正が必要です。',
    userAction: 'needs_fix',
    userComment: '要修正。構造図の通り芯X3を確認',
    evidenceFile: 'file-1',
    evidencePage: 2,
    boundingBox: { x: 280, y: 220, width: 70, height: 55 },
    polygon: [[280, 220], [350, 220], [350, 275], [280, 275]],
  },
  {
    id: 'finding-3',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '配筋整合性',
    findingType: '配筋整合性',
    aiJudgment: 'WARNING',
    confidence: 0.72,
    aiComment: 'C1柱（X2-Y3交点）の主筋本数が異なる可能性があります（構造: 12-D25, 施工: 不明瞭）',
    aiInference: '画像解析により配筋パターンを検出しましたが、施工図の表記が不明瞭なため確定判定ができません。現場確認を推奨します。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 1,
    boundingBox: { x: 180, y: 280, width: 90, height: 70 },
    polygon: [[180, 280], [270, 280], [270, 350], [180, 350]],
  },
  {
    id: 'finding-4',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '柱寸法整合性',
    findingType: '柱寸法整合性',
    aiJudgment: 'OK',
    confidence: 0.92,
    aiComment: 'C2柱（X4-Y1交点）の断面寸法が一致しています（600×600）',
    aiInference: 'C2柱の断面寸法600×600mmが構造図と施工図で正確に一致していることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 3,
    boundingBox: { x: 350, y: 120, width: 65, height: 50 },
    polygon: [[350, 120], [415, 120], [415, 170], [350, 170]],
  },
  {
    id: 'finding-5',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯間隔',
    findingType: '通り芯間隔',
    aiJudgment: 'OK',
    confidence: 0.96,
    aiComment: 'X1-X2間の通り芯間隔が正確です（4800mm）',
    aiInference: 'X1-X2間の通り芯間隔4800mmが設計図通りであることを確認しました。測定精度は高い信頼度です。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 1,
    boundingBox: { x: 420, y: 180, width: 75, height: 60 },
    polygon: [[420, 180], [495, 180], [495, 240], [420, 240]],
  },
  {
    id: 'finding-6',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '基礎梁配筋',
    findingType: '基礎梁配筋',
    aiJudgment: 'NG',
    confidence: 0.71,
    aiComment: 'F1基礎梁（X2-Y1からX3-Y1）の主筋配置が不明確です。要確認',
    aiInference: '基礎梁F1の主筋配置について、施工図と構造図の間に不整合が検出されました。詳細確認が必要です。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 2,
    boundingBox: { x: 150, y: 320, width: 85, height: 55 },
    polygon: [[150, 320], [235, 320], [235, 375], [150, 375]],
  },
  {
    id: 'finding-7',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '梁断面整合性',
    findingType: '梁断面整合性',
    aiJudgment: 'OK',
    confidence: 0.94,
    aiComment: 'G1梁（X1-Y2からX3-Y2スパン）の断面寸法が一致しています（400×800）',
    aiInference: 'G1梁の断面400×800mmが設計通りであることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 4,
    boundingBox: { x: 250, y: 100, width: 70, height: 45 },
    polygon: [[250, 100], [320, 100], [320, 145], [250, 145]],
  },
  {
    id: 'finding-8',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '柱配筋整合性',
    findingType: '柱配筋整合性',
    aiJudgment: 'OK',
    confidence: 0.89,
    aiComment: 'C1柱（X1-Y1交点）の配筋パターンが一致しています（16-D25 + D10@100）',
    aiInference: 'C1柱の配筋パターン（主筋16-D25、帯筋D10@100）が設計図と一致していることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 3,
    boundingBox: { x: 320, y: 250, width: 80, height: 65 },
    polygon: [[320, 250], [400, 250], [400, 315], [320, 315]],
  },
  {
    id: 'finding-9',
    jobId: 'job-001',
    fileId: 'file-1',
    type: '通り芯間隔',
    findingType: '通り芯間隔',
    aiJudgment: 'OK',
    confidence: 0.97,
    aiComment: 'Y軸方向の通り芯間隔が正確です（Y1-Y2: 6000mm, Y2-Y3: 6000mm）',
    aiInference: 'Y軸方向の通り芯間隔が設計通り6000mmであることを高精度で確認しました。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 2,
    boundingBox: { x: 180, y: 380, width: 75, height: 50 },
    polygon: [[180, 380], [255, 380], [255, 430], [180, 430]],
  },
  {
    id: 'finding-10',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '基礎レベル整合性',
    findingType: '基礎レベル整合性',
    aiJudgment: 'NG',
    confidence: 0.81,
    aiComment: 'F1基礎（X2-Y2交点）の天端レベル表記が10mm異なります（構造: FL-500, 施工: FL-490）',
    aiInference: '基礎天端レベルに10mmの差異を検出しました。この誤差は施工精度に影響する可能性があります。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-1',
    evidencePage: 1,
    boundingBox: { x: 450, y: 300, width: 70, height: 55 },
    polygon: [[450, 300], [520, 300], [520, 355], [450, 355]],
  },
  {
    id: 'finding-11',
    jobId: 'job-001',
    fileId: 'file-2',
    type: 'スラブ厚整合性',
    findingType: 'スラブ厚整合性',
    aiJudgment: 'OK',
    confidence: 0.93,
    aiComment: '基礎スラブ厚が一致しています（150mm）',
    aiInference: '基礎スラブ厚150mmが構造図と施工図で一致していることを確認しました。',
    userAction: 'confirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 4,
    boundingBox: { x: 100, y: 420, width: 85, height: 50 },
    polygon: [[100, 420], [185, 420], [185, 470], [100, 470]],
  },
  {
    id: 'finding-12',
    jobId: 'job-001',
    fileId: 'file-2',
    type: '梁主筋配筋',
    findingType: '梁主筋配筋',
    aiJudgment: 'OK',
    confidence: 0.91,
    aiComment: 'G2梁（X4-Y3からX5-Y3）の主筋配置が正確です（上筋: 4-D22, 下筋: 3-D22）',
    aiInference: 'G2梁の主筋配置（上筋4-D22、下筋3-D22）が設計図通りであることを確認しました。',
    userAction: 'unconfirmed',
    userComment: '',
    evidenceFile: 'file-2',
    evidencePage: 5,
    boundingBox: { x: 380, y: 380, width: 80, height: 55 },
    polygon: [[380, 380], [460, 380], [460, 435], [380, 435]],
  },
];

// Simulated async processing
export const simulateJobProcessing = (jobId, onProgress) => {
  return new Promise((resolve) => {
    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.random() * 15;
      if (progress >= 100) {
        progress = 100;
        clearInterval(interval);
        onProgress(100);
        resolve();
      } else {
        onProgress(Math.floor(progress));
      }
    }, 1000);
  });
};

// Helper functions
export const getUserById = (userId) => users.find(u => u.id === userId);
export const getTenantById = (tenantId) => tenants.find(t => t.id === tenantId);
export const getJobById = (jobId) => mockJobs.find(j => j.id === jobId);
export const getJobsByTenant = (tenantId) => mockJobs.filter(j => j.tenantId === tenantId);
export const getJobsByUser = (userId) => mockJobs.filter(j => j.userId === userId);
export const getInspectionResults = (jobId) => mockInspectionResults.filter(r => r.jobId === jobId);
export const getBOMResults = (jobId) => mockBOMResults.filter(r => r.jobId === jobId);
export const getScanResults = (jobId) => mockScanResults.filter(r => r.jobId === jobId);

// Backwards compatibility alias
export const getSearchResults = getScanResults;
